hadd comb_BestJetJet2W_M_WprimeLeft_Histos-onebtags_7TeVcuts.root *_BestJetJet2W_M_WprimeLeft_Histos-onebtags_7TeVcuts.root
hadd comb_BestJetJet2W_M_WprimeLeft_Histos-twobtags_7TeVcuts.root *_BestJetJet2W_M_WprimeLeft_Histos-twobtags_7TeVcuts.root
hadd comb_BestJetJet2W_M_WprimeMix_Histos-onebtags_7TeVcuts.root *_BestJetJet2W_M_WprimeMix_Histos-onebtags_7TeVcuts.root
hadd comb_BestJetJet2W_M_WprimeMix_Histos-twobtags_7TeVcuts.root *_BestJetJet2W_M_WprimeMix_Histos-twobtags_7TeVcuts.root
hadd comb_BestJetJet2W_M_WprimeModRight_Histos-onebtags_7TeVcuts.root *_BestJetJet2W_M_WprimeModRight_Histos-onebtags_7TeVcuts.root
hadd comb_BestJetJet2W_M_WprimeModRight_Histos-twobtags_7TeVcuts.root *_BestJetJet2W_M_WprimeModRight_Histos-twobtags_7TeVcuts.root
hadd comb_BestJetJet2W_M_WprimeRight_Histos-onebtags_7TeVcuts.root *_BestJetJet2W_M_WprimeRight_Histos-onebtags_7TeVcuts.root
hadd comb_BestJetJet2W_M_WprimeRight_Histos-twobtags_7TeVcuts.root *_BestJetJet2W_M_WprimeRight_Histos-twobtags_7TeVcuts.root

hadd comb_BestJetJet2W_M_WprimeLeft_Histos-onetwobtags_7TeVcuts.root comb_BestJetJet2W_M_WprimeLeft_Histos-*tags_7TeVcuts.root
hadd comb_BestJetJet2W_M_WprimeMix_Histos-onetwobtags_7TeVcuts.root comb_BestJetJet2W_M_WprimeMix_Histos-*tags_7TeVcuts.root
hadd comb_BestJetJet2W_M_WprimeModRight_Histos-onetwobtags_7TeVcuts.root comb_BestJetJet2W_M_WprimeModRight_Histos-*tags_7TeVcuts.root
hadd comb_BestJetJet2W_M_WprimeRight_Histos-onetwobtags_7TeVcuts.root comb_BestJetJet2W_M_WprimeRight_Histos-*tags_7TeVcuts.root

hadd electron_BestJetJet2W_M_WprimeLeft_Histos-onetwobtags_7TeVcuts.root electron_BestJetJet2W_M_WprimeLeft_Histos-onebtags_7TeVcuts.root electron_BestJetJet2W_M_WprimeLeft_Histos-twobtags_7TeVcuts.root
hadd electron_BestJetJet2W_M_WprimeMix_Histos-onetwobtags_7TeVcuts.root electron_BestJetJet2W_M_WprimeMix_Histos-onebtags_7TeVcuts.root electron_BestJetJet2W_M_WprimeMix_Histos-twobtags_7TeVcuts.root
hadd electron_BestJetJet2W_M_WprimeModRight_Histos-onetwobtags_7TeVcuts.root electron_BestJetJet2W_M_WprimeModRight_Histos-onebtags_7TeVcuts.root electron_BestJetJet2W_M_WprimeModRight_Histos-twobtags_7TeVcuts.root
hadd electron_BestJetJet2W_M_WprimeRight_Histos-onetwobtags_7TeVcuts.root electron_BestJetJet2W_M_WprimeRight_Histos-onebtags_7TeVcuts.root electron_BestJetJet2W_M_WprimeRight_Histos-twobtags_7TeVcuts.root

hadd muon_BestJetJet2W_M_WprimeLeft_Histos-onetwobtags_7TeVcuts.root muon_BestJetJet2W_M_WprimeLeft_Histos-onebtags_7TeVcuts.root muon_BestJetJet2W_M_WprimeLeft_Histos-twobtags_7TeVcuts.root
hadd muon_BestJetJet2W_M_WprimeMix_Histos-onetwobtags_7TeVcuts.root muon_BestJetJet2W_M_WprimeMix_Histos-onebtags_7TeVcuts.root muon_BestJetJet2W_M_WprimeMix_Histos-twobtags_7TeVcuts.root
hadd muon_BestJetJet2W_M_WprimeModRight_Histos-onetwobtags_7TeVcuts.root muon_BestJetJet2W_M_WprimeModRight_Histos-onebtags_7TeVcuts.root muon_BestJetJet2W_M_WprimeModRight_Histos-twobtags_7TeVcuts.root
hadd muon_BestJetJet2W_M_WprimeRight_Histos-onetwobtags_7TeVcuts.root muon_BestJetJet2W_M_WprimeRight_Histos-onebtags_7TeVcuts.root muon_BestJetJet2W_M_WprimeRight_Histos-twobtags_7TeVcuts.root
